[package]
name = "simplex"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]

std = []

[dependencies]
slice-partitions.workspace = true

heapless.workspace = true
thiserror.workspace = true

[lints]
workspace = true
